 ## Program specific info
command:
   - /usr/bin/python3
   - ${program}
   - ${args}
program: main.py
docker_image: nvcr.io/nvidian/nvr-rock/raml


project: roml
sweep_name: kd_batch_base
method: grid
parameters:
  use_wandb:
    value: True
  env-type:
    values: [khazad_dum_varibad]
  exp_label:
    values: [kd_cvrbad_alpha]
  alpha:
    values: [0.05]
  tail:
    values: [1]
  seed:
    values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

# Example: python main.py --env-type humanoid_mass_varibad --exp_label humm_varibad --cem 0 --seed 10
