## Program specific info
program: main.py
docker_image: nvcr.io/nvidian/nvr-rock/raml

## Sweep specific info
project: roml
sweep_name: humm_last_seeds
method: grid
parameters:
  use_wandb:
    value: True
  env-type:
    values: [humanoid_mass_varibad]
  cem:
    values: [0, 1]
  seed:
    values: [23,24,25,26,27,28,29]

# Example: python main.py --env-type humanoid_mass_varibad --exp_label humm_varibad --cem 0 --seed 10
